### ISSUE TITLE
Paper reference for Readme

### ISSUE THREAD

**Issue by pmcgee69** [statusfailed/cartographer-har#1]
The Cost of Compositionality: A High-Performance Implementation of String Diagram Composition
Paul Wilson, Fabio Zanasi
https://arxiv.org/abs/2105.09257

**Comment by osdev-in** [comment]
Hey @pmcgee69 , Can I help with this ?

**Comment by statusfailed** [comment]
Added- thanks for the reminder!

**Comment by pmcgee69** [comment]
Maybe a link to the YouTube video of the ACT 2021 presentation also ... ?

**Comment by statusfailed** [comment]
> Maybe a link to the YouTube video of the ACT 2021 presentation also ... ?

Good idea- done that too.
